(function(){
'use strict';
const $=s=>document.querySelector(s), $$=s=>Array.from(document.querySelectorAll(s));
const PIECE={wK:'♔︎',wQ:'♕︎',wR:'♖︎',wB:'♗︎',wN:'♘︎',wP:'♙︎',bK:'♚︎',bQ:'♛︎',bR:'♜︎',bB:'♝︎',bN:'♞︎',bP:'♟︎'};
let mode='ai',level=2,board=[],turn='w',selected=null,targets=[],orientation='w',locked=false,history=[],snapshots=[],players={},sound=true;
let castle={wK:true,wQ:true,bK:true,bQ:true},ep=null;
let db=null,auth=null,room=null,myUid=null,myColor=null,hostId=null,roomRef=null;
function initial(){return ['bR','bN','bB','bQ','bK','bB','bN','bR',...Array(8).fill('bP'),...Array(32).fill(null),...Array(8).fill('wP'),'wR','wN','wB','wQ','wK','wB','wN','wR']}
function show(id){$$('.screen').forEach(x=>x.classList.remove('active'));$('#'+id).classList.add('active')}
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),1800)}
function rc(i){return [Math.floor(i/8),i%8]} const ix=(r,c)=>r*8+c, inside=(r,c)=>r>=0&&r<8&&c>=0&&c<8, color=p=>p&&p[0], type=p=>p&&p[1];
function tone(f){if(!sound)return;try{const A=window.AudioContext||window.webkitAudioContext,a=new A(),o=a.createOscillator(),g=a.createGain();o.frequency.value=f;g.gain.value=.04;o.connect(g);g.connect(a.destination);o.start();g.gain.exponentialRampToValueAtTime(.001,a.currentTime+.08);o.stop(a.currentTime+.08)}catch(e){}}
function pseudo(b,i,attack){const p=b[i];if(!p)return[];const co=color(p),t=type(p),[r,c]=rc(i),out=[],dir=co==='w'?-1:1;const add=(rr,cc)=>{if(!inside(rr,cc))return false;const q=b[ix(rr,cc)];if(!q){out.push(ix(rr,cc));return true}if(color(q)!==co)out.push(ix(rr,cc));return false};
 if(t==='P'){const rr=r+dir;if(attack){[-1,1].forEach(dc=>{if(inside(rr,c+dc))out.push(ix(rr,c+dc))});return out}if(inside(rr,c)&&!b[ix(rr,c)]){out.push(ix(rr,c));if(r===(co==='w'?6:1)&&!b[ix(r+2*dir,c)])out.push(ix(r+2*dir,c))}[-1,1].forEach(dc=>{if(inside(rr,c+dc)){const j=ix(rr,c+dc);if((b[j]&&color(b[j])!==co)||j===ep)out.push(j)}})}
 else if(t==='N')[[2,1],[2,-1],[-2,1],[-2,-1],[1,2],[1,-2],[-1,2],[-1,-2]].forEach(d=>add(r+d[0],c+d[1]));
 else if(t==='K'){for(let dr=-1;dr<=1;dr++)for(let dc=-1;dc<=1;dc++)if(dr||dc)add(r+dr,c+dc);if(!attack&&!inCheck(b,co)){const base=co==='w'?60:4;if(i===base){if(castle[co+'K']&&!b[base+1]&&!b[base+2]&&b[base+3]===co+'R'&&!attacked(b,base+1,co)&&!attacked(b,base+2,co))out.push(base+2);if(castle[co+'Q']&&!b[base-1]&&!b[base-2]&&!b[base-3]&&b[base-4]===co+'R'&&!attacked(b,base-1,co)&&!attacked(b,base-2,co))out.push(base-2)}}}
 else{const ds=t==='B'?[[1,1],[1,-1],[-1,1],[-1,-1]]:t==='R'?[[1,0],[-1,0],[0,1],[0,-1]]:[[1,1],[1,-1],[-1,1],[-1,-1],[1,0],[-1,0],[0,1],[0,-1]];ds.forEach(d=>{let rr=r+d[0],cc=c+d[1];while(inside(rr,cc)){if(!add(rr,cc))break;rr+=d[0];cc+=d[1]}})}return out}
function attacked(b,sq,def){for(let i=0;i<64;i++)if(b[i]&&color(b[i])!==def&&pseudo(b,i,true).includes(sq))return true;return false}
function inCheck(b,co){const k=b.indexOf(co+'K');return k>=0&&attacked(b,k,co)}
function simulate(b,a,z){const n=b.slice(),p=n[a];if(type(p)==='P'&&z===ep&&!n[z])n[z+(color(p)==='w'?8:-8)]=null;n[z]=p;n[a]=null;if(type(p)==='K'&&Math.abs(z-a)===2){const rf=z>a?a+3:a-4,rt=z>a?a+1:a-1;n[rt]=n[rf];n[rf]=null}return n}
function legal(i){const co=color(board[i]);return pseudo(board,i,false).filter(z=>!inCheck(simulate(board,i,z),co))}
function allMoves(b,co){const save=board;board=b;let a=[];for(let i=0;i<64;i++)if(color(b[i])===co)legal(i).forEach(z=>a.push([i,z]));board=save;return a}
function render(){const el=$('#board');el.innerHTML='';let order=Array.from({length:64},(_,i)=>i);if(orientation==='b')order.reverse();order.forEach(i=>{const [r,c]=rc(i),s=document.createElement('div');s.className='square '+((r+c)%2?'dark':'light');if(i===selected)s.classList.add('selected');if(targets.includes(i))s.classList.add(board[i]?'capture':'move');if(board[i]){const q=document.createElement('span');q.className='piece '+(color(board[i])==='w'?'whitePiece':'blackPiece');q.textContent=PIECE[board[i]];s.appendChild(q)}s.onclick=()=>clickSquare(i);el.appendChild(s)});$('#status').textContent=(turn==='w'?'Blancs':'Noirs')+' jouent'+(inCheck(board,turn)?' — Échec !':'');$('#history').textContent=history.join('  ');const wn=players.white?.name||'Blancs',bn=players.black?.name||(mode==='ai'?'IA':'Noirs');$('#bottomPlayer').textContent=orientation==='w'?wn:bn;$('#topPlayer').textContent=orientation==='w'?bn:wn;$('#undoBtn').style.display=mode==='online'?'none':'block'}
function clickSquare(i){if(locked)return;if(mode==='online'&&myColor!==turn)return;if(mode==='ai'&&turn==='b')return;if(selected!==null&&targets.includes(i)){move(selected,i,true);return}if(color(board[i])===turn){selected=i;targets=legal(i);render()}else{selected=null;targets=[];render()}}
function snapshot(){return{board:board.slice(),turn,history:history.slice(),castle:{...castle},ep}}
function move(a,z,publish){const p=board[a],capture=!!board[z]||(type(p)==='P'&&z===ep&&!board[z]);if(mode!=='online')snapshots.push(snapshot());const oldEp=ep;board=simulate(board,a,z);if(type(p)==='K'){castle[color(p)+'K']=false;castle[color(p)+'Q']=false}if(type(p)==='R'){if(a===63)castle.wK=false;if(a===56)castle.wQ=false;if(a===7)castle.bK=false;if(a===0)castle.bQ=false}ep=null;if(type(p)==='P'&&Math.abs(z-a)===16)ep=(a+z)/2;const zr=rc(z)[0];if(type(p)==='P'&&(zr===0||zr===7))board[z]=color(p)+'Q';history.push((turn==='w'?'♙ ':'♟ ')+String.fromCharCode(97+rc(z)[1])+(8-rc(z)[0]));turn=turn==='w'?'b':'w';selected=null;targets=[];tone(capture?180:430);render();const end=endState();if(end){finish(end);if(mode==='online'&&publish)sync(end);return}if(mode==='online'&&publish)sync('');if(mode==='ai'&&turn==='b'){locked=true;setTimeout(aiMove,500)}}
function endState(){if(allMoves(board,turn).length)return'';return inCheck(board,turn)?(turn==='w'?'Noirs gagnent par échec et mat':'Blancs gagnent par échec et mat'):'Partie nulle — pat'}
function finish(t){locked=true;$('#winnerText').textContent=t;$('#winner').classList.remove('hidden');if(t.indexOf('nulle')<0)confetti()}
function newGame(){board=initial();turn='w';selected=null;targets=[];history=[];snapshots=[];castle={wK:true,wQ:true,bK:true,bQ:true};ep=null;locked=false;$('#winner').classList.add('hidden');render();show('game')}
function value(b){const v={P:100,N:320,B:330,R:500,Q:900,K:20000};return b.reduce((s,p)=>s+(p?(color(p)==='b'?1:-1)*v[type(p)]:0),0)}
function aiMove(){const ms=allMoves(board,'b');if(!ms.length){locked=false;return}let m=ms[Math.floor(Math.random()*ms.length)];if(level>1){let best=-1e9;ms.forEach(x=>{const sc=value(simulate(board,x[0],x[1]))+Math.random()*12;if(sc>best){best=sc;m=x}})}locked=false;move(m[0],m[1],false)}
function initFirebase(){if(db)return true;if(!window.firebase){toast('Firebase ne s’est pas chargé. Vérifiez la connexion Internet.');return false}try{const cfg={apiKey:'AIzaSyBG6oid29bMq8GVvBkNvPtSDZTRO5K09uk',authDomain:'focus-game-1c7ee.firebaseapp.com',databaseURL:'https://focus-game-1c7ee-default-rtdb.europe-west1.firebasedatabase.app',projectId:'focus-game-1c7ee',storageBucket:'focus-game-1c7ee.firebasestorage.app',messagingSenderId:'856695121197',appId:'1:856695121197:web:34599f1ace92ac56499fa4'};if(!firebase.apps.length)firebase.initializeApp(cfg);auth=firebase.auth();db=firebase.database();return true}catch(e){toast('Erreur Firebase : '+e.message);return false}}
async function login(){if(!initFirebase())throw Error('Firebase indisponible');if(!auth.currentUser)await auth.signInAnonymously();myUid=auth.currentUser.uid}
function roomCode(){return Math.random().toString(36).slice(2,8).toUpperCase()}
function listen(){if(roomRef)roomRef.off();roomRef=db.ref('chessRooms/'+room);roomRef.on('value',snap=>{const d=snap.val();if(!d){toast('Salon fermé');show('home');return}hostId=d.hostId;$('#roomCode').textContent=room;const ps=d.players||{},arr=Object.entries(ps);$('#players').innerHTML=arr.map(([u,p])=>'<p>'+(p.color==='w'?'♔':'♚')+' '+escapeHtml(p.name)+(p.connected===false?' (déconnecté)':'')+'</p>').join('');$('#launchOnline').disabled=!(myUid===hostId&&arr.length>=2);$('#lobbyMsg').textContent=arr.length>=2?'Les deux joueurs sont prêts.':'En attente d’un adversaire…';players={};arr.forEach(([u,p])=>players[p.color==='w'?'white':'black']=p);if(d.phase==='playing'&&d.game){applyRemote(d.game);show('game')}if(d.result&&$('#winner').classList.contains('hidden'))finish(d.result)})}
function escapeHtml(x){return String(x).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function state(){return{board:board.map(x=>x||'--'),turn,history,castle,ep:ep===null?-1:ep,version:Date.now()}}
function sync(result){if(room&&db)db.ref('chessRooms/'+room).update({game:state(),result:result||''})}
function applyRemote(g){if(!g||!g.board)return;board=g.board.map(x=>x==='--'?null:x);turn=g.turn;history=g.history||[];castle=g.castle||castle;ep=g.ep===-1?null:g.ep;orientation=myColor||'w';locked=false;selected=null;targets=[];render()}
async function leaveRoom(){if(room&&db&&myUid){try{if(myUid===hostId)await db.ref('chessRooms/'+room).remove();else await db.ref('chessRooms/'+room+'/players/'+myUid).remove()}catch(e){}}if(roomRef)roomRef.off();roomRef=null;room=null}
$('#aiBtn').onclick=()=>{mode='ai';$('#setupTitle').textContent='Contre l’IA';$('#aiSetup').style.display='block';$('#p2Label').style.display='none';show('setup')};
$('#localBtn').onclick=()=>{mode='local';$('#setupTitle').textContent='2 joueurs local';$('#aiSetup').style.display='none';$('#p2Label').style.display='grid';show('setup')};
$('#onlineBtn').onclick=()=>{mode='online';show('online')};$$('.back').forEach(b=>b.onclick=()=>show('home'));
$('#startBtn').onclick=()=>{level=Number($('#level').value);players={white:{name:$('#playerName').value||'Joueur 1'},black:{name:mode==='ai'?'IA':($('#player2Name').value||'Joueur 2')}};orientation='w';newGame()};
$('#flipBtn').onclick=()=>{if(mode==='online')return toast('En ligne, vos pièces restent en bas.');orientation=orientation==='w'?'b':'w';render()};
$('#undoBtn').onclick=()=>{if(!snapshots.length)return;let n=(mode==='ai'&&turn==='w'&&snapshots.length>=2)?2:1,st;while(n--&&snapshots.length)st=snapshots.pop();if(st){board=st.board;turn=st.turn;history=st.history;castle=st.castle;ep=st.ep;locked=false;$('#winner').classList.add('hidden');render()}};
$('#resignBtn').onclick=()=>finish(turn==='w'?'Blancs abandonnent — Noirs gagnent':'Noirs abandonnent — Blancs gagnent');$('#gameHome').onclick=$('#winnerHome').onclick=()=>{if(confirm('Quitter la partie ?')){leaveRoom();show('home')}};$('#rematch').onclick=()=>{if(mode==='online'){if(myUid!==hostId)return toast('L’hôte lance la revanche.');newGame();sync('')}else newGame()};
$('#createBtn').onclick=async()=>{try{await login();room=roomCode();hostId=myUid;myColor='w';const name=$('#onlineName').value||'Joueur';await db.ref('chessRooms/'+room).set({hostId,phase:'lobby',createdAt:firebase.database.ServerValue.TIMESTAMP,players:{[myUid]:{name,color:'w',connected:true}}});db.ref('chessRooms/'+room+'/players/'+myUid+'/connected').onDisconnect().set(false);listen();show('lobby')}catch(e){$('#onlineMsg').textContent=e.message}};
$('#joinBtn').onclick=async()=>{try{await login();room=$('#roomInput').value.trim().toUpperCase();if(!room)return toast('Entrez le code du salon');const snap=await db.ref('chessRooms/'+room).once('value');if(!snap.exists())return toast('Salon introuvable');const d=snap.val(),ps=d.players||{};if(Object.keys(ps).length>=2&&!ps[myUid])return toast('Salon complet');hostId=d.hostId;myColor=myUid===hostId?'w':'b';await db.ref('chessRooms/'+room+'/players/'+myUid).set({name:$('#onlineName').value||'Joueur',color:myColor,connected:true});db.ref('chessRooms/'+room+'/players/'+myUid+'/connected').onDisconnect().set(false);listen();show('lobby')}catch(e){toast(e.message)}};
$('#launchOnline').onclick=async()=>{if(myUid!==hostId)return;board=initial();turn='w';history=[];castle={wK:true,wQ:true,bK:true,bQ:true};ep=null;orientation=myColor;locked=false;await db.ref('chessRooms/'+room).update({phase:'playing',game:state(),result:''})};$('#leaveLobby').onclick=async()=>{await leaveRoom();show('home')};
$('#shareBtn').onclick=async()=>{const url=location.href.split('?')[0]+'?room='+room;try{if(navigator.share)await navigator.share({title:'Partie d’échecs',text:'Rejoins mon salon '+room,url});else{await navigator.clipboard.writeText(url);toast('Lien copié')}}catch(e){}};
$('#menuBtn').onclick=()=>$('#drawer').classList.add('open');$('#closeMenu').onclick=()=>$('#drawer').classList.remove('open');$('#soundBtn').onclick=()=>{sound=!sound;$('#soundBtn').textContent=sound?'🔊':'🔇'};$('#rulesBtn').onclick=()=>modal('<h2>Règles des échecs</h2><p>Les Blancs commencent. Le but est de mettre le roi adverse en échec et mat.</p><p>Roque, prise en passant, promotion automatique en dame et pat sont pris en charge.</p>');$('#settingsBtn').onclick=()=>modal('<h2>Paramètres</h2><p>Son : '+(sound?'activé':'désactivé')+'</p>');$('#closeModal').onclick=()=>$('#modal').classList.add('hidden');function modal(h){$('#modalContent').innerHTML=h;$('#modal').classList.remove('hidden');$('#drawer').classList.remove('open')}
function confetti(){const c=$('#confetti'),x=c.getContext('2d');c.width=innerWidth;c.height=innerHeight;const a=Array.from({length:80},()=>({x:Math.random()*c.width,y:-20-Math.random()*300,v:2+Math.random()*4,s:3+Math.random()*5,h:Math.random()*360}));let n=0;(function f(){x.clearRect(0,0,c.width,c.height);a.forEach(p=>{p.y+=p.v;x.fillStyle='hsl('+p.h+',70%,55%)';x.fillRect(p.x,p.y,p.s*2,p.s)});if(n++<160)requestAnimationFrame(f);else x.clearRect(0,0,c.width,c.height)})()}
const qp=new URLSearchParams(location.search).get('room');if(qp){$('#roomInput').value=qp.toUpperCase();show('online')}board=initial();render();
})();
